name: Build Kaldi

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - run: echo hello > artifact.txt

      - uses: actions/upload-artifact@v1
        with:
          name: test-artifact
          path: artifact.txt