name: Build Kaldi

on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - run: ./linux/setup-dependencies.sh
      - run: ./linux/setup-kaldi.sh
      - run: ./linux/build.sh
